### ISSUE TITLE
Cannot apply changes in the project settings dialog

### ISSUE THREAD

**Issue by IoeCmcomc** [alejandroautalan/pygubu-designer#253]
**Describe the bug**
Clicking the "OK" button in the project settings dialog do nothing visually, which make it impossible to change the project settings.

**To Reproduce**
1. Open any file
2. From the menu bar, click on Project > Settings
3. (Optional) Change something in the dialog, such as the project name
4. Click the "OK" button
5. Nothing happened

**Expected behavior**
The dialog should close, and the changes should be saved.

**Your Environment:**
 - OS: Windows 11 23H2
 - Python version: 3.8.10
 - Pygubu version: 0.35.1
 - Designer version: 0.39.2

**Additional context**
Here's the full console output:
```
python: 3.8.10 on win32
tk: 8.6
pygubu: 0.35.1
pygubu-designer: 0.39.2
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubudesigner\services\projectsettings.py", line 203, in btn_apply_clicked
    all_valid, new_settings = self.process_forms()
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubudesigner\services\projectsettings.py", line 179, in process_forms
    form.submit()
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubu\forms\form.py", line 99, in submit
    self.submit_init()
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubu\forms\form.py", line 112, in submit_init
    field.widget.wmark_invalid(False)
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubu\forms\tkwidget.py", line 75, in wmark_invalid
    self.view_manager.mark_invalid(self, state)
  File "D:\Python\NBSTool\.venv\lib\site-packages\pygubu\forms\ttkwidget.py", line 22, in mark_invalid
    style = style.removeprefix("Error.")
AttributeError: 'str' object has no attribute 'removeprefix'
```

**Comment by alejandroautalan** [comment]
Hello @IoeCmcomc, thanks for trying pygubu and for the bug report.
I will try to fix it ASAP.

Regards
Alejandro A.
