### ISSUE TITLE
Fails to start (Linux)

### ISSUE THREAD

**Issue by Itai-Nelken** [alejandroautalan/pygubu-designer#26]
I installed pygubu-designer on my Raspberry Pi running TwisterOS (improvend and themed RPiOS - Debian based) with `pip install pygubu-designer`.
but when starting from terminal with `pygubu-designer` I get the following output and the proccess exits:
```bash
pi@Twisterpi4-ultra-4gb:~ $ pygubu-designer
python: 2.7.16 on linux2
pygubu: 0.10.4
pygubu-designer: 0.12
Traceback (most recent call last):
  File "/home/pi/.local/bin/pygubu-designer", line 10, in <module>
    sys.exit(start_pygubu())
  File "/home/pi/.local/lib/python2.7/site-packages/pygubudesigner/main.py", line 657, in start_pygubu
    app = PygubuDesigner()
  File "/home/pi/.local/lib/python2.7/site-packages/pygubudesigner/main.py", line 285, in __init__
    self._setup_styles()
  File "/home/pi/.local/lib/python2.7/site-packages/pygubudesigner/main.py", line 326, in _setup_styles
    image=StockImage.get('mglass'))
  File "/home/pi/.local/lib/python2.7/site-packages/pygubu/stockimage.py", line 177, in get
    raise StockImageException('StockImage: %s not registered.' % rkey)
pygubu.stockimage.StockImageException: StockImage: mglass not registered.
pi@Twisterpi4-ultra-4gb:~ $ 
```

**Comment by alejandroautalan** [comment]
Hi  Itai Nelken, thanks for trying pygubu and for the bug report.

This is an error in the pypi package generated for python 2.7.  It will be fixed on next version.
In the meantime, you can fix it manually renaming the file:

    /home/pi/.local/lib/python2.7/site-packages/pygubudesigner/images/mglass_.gif

To:

    /home/pi/.local/lib/python2.7/site-packages/pygubudesigner/images/mglass.gif

Let me know if this helps.

Regards
Alejandro A.

**Comment by Itai-Nelken** [comment]
that works! thanks a lot for making this tool!
