### ISSUE TITLE
Not starting on macOS

### ISSUE THREAD

**Issue by tkshnwesper** [alejandroautalan/pygubu-designer#280]
**Describe the bug**
Getting this error:

```
python: 3.12.7 on darwin
tk: 9.0
pygubu: 0.35.6
pygubu-designer: 0.39.3
Traceback (most recent call last):
  File "/Users/example/python-venvs/default/bin/pygubu-designer", line 8, in <module>
    sys.exit(start_pygubu())
             ^^^^^^^^^^^^^^
  File "/Users/example/python-venvs/default/lib/python3.12/site-packages/pygubudesigner/main.py", line 991, in start_pygubu
    app = PygubuDesigner()
          ^^^^^^^^^^^^^^^^
  File "/Users/example/python-venvs/default/lib/python3.12/site-packages/pygubudesigner/main.py", line 252, in __init__
    self.tree_editor = WidgetsTreeEditor(self)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/example/python-venvs/default/lib/python3.12/site-packages/pygubudesigner/uitreeeditor.py", line 105, in __init__
    self.config_filter()
  File "/Users/example/python-venvs/default/lib/python3.12/site-packages/pygubudesigner/uitreeeditor.py", line 468, in config_filter
    self.filtervar.trace("w", on_filtervar_changed)
  File "/usr/local/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 506, in trace_variable
    self._tk.call("trace", "variable", self._name, mode, cbname)
_tkinter.TclError: bad option "variable": must be add, info, or remove
```

**To Reproduce**
1. Run `pygubu-designer`

**Expected behavior**
Should open normally

**Your Environment (please complete the following information):**
 - OS: macOS Monterey
 - Python version: 3.12
 - Pygubu version: 0.35.6
 - Designer version: 0.39.3

**Comment by alejandroautalan** [comment]
Hello @tkshnwesper, thanks for trying pygubu and for the bug report.

It happens with tk: 9.0

I will fix it ASAP.
Regards

Alejandro A.

**Comment by tkshnwesper** [comment]
I followed your steps, and it works now! 👍
